"""_calc sheet: hidden engine blocks.

Sections, top to bottom:
  1. Results table (rows 4..21) — one row per tbl_LR row, read by Portfolio.
  2. 18 combo engine blocks (one per tbl_LR row), stride 54 rows.
  3. Scenario-transformed rate logs (4 x 9 columns, 40 rows) + 4 scenario blocks
     for the SELECTED combo.
  4. Attribution rank/transformed logs + 3 attribution blocks (magnitude,
     timing, actual-mod) for the selected combo.
  5. Solver base block (taken rows only) with cumulative columns for Mode B.

Every block is emitted by sheets_engine.write_cohort_block so the formula
pattern is identical to the visible Rate Engine. Dynamic anchors are stored in
ctx.lay_dyn for the visible sheets (Scenarios / Solver / Attribution) to link.
"""

from __future__ import annotations

from .build_workbook import Ctx, Layout as L, SHEETS
from .sheets_engine import LogRefs, write_cohort_block, write_mod_anchor_cells
from .xlstyle import (FMT_IDX, FMT_INT, FMT_MOD, GREY_DARK, col, font, formula, label,
                      put, quote_sheet)

RL = quote_sheet(SHEETS.RATE_LOG)   # the rate-log rows the scenario/attr logs mirror


def _grey(ws, addr):
    ws[addr].font = font(GREY_DARK, size=9)


def f_grey(ws, addr, f, fmt="General"):
    formula(ws, addr, f, fmt=fmt)
    _grey(ws, addr)


def build_calc(ctx: Ctx):
    ws = ctx.wb["_calc"]
    put(ws, "A1",
        "_calc (hidden): per-combo engine blocks generated by src/build_workbook.py. "
        "Same formula pattern as the visible Rate Engine; do not edit.",
        fnt=font(GREY_DARK, bold=True, size=9))

    # ------------------------------------------------------------------
    # 2. Combo engine blocks (written first so the results table can link)
    # ------------------------------------------------------------------
    block_tops = []
    for i in range(L.LR_ROWS):
        n = i + 1
        t = L.CALC_BLOCK_FIRST + i * L.CALC_BLOCK_STRIDE
        block_tops.append(t)
        # block header row t: key, state, T, seasonality helpers, guarded mod inputs
        f_grey(ws, f"A{t}", f"=INDEX(lr_key,{n})")
        f_grey(ws, f"B{t}", f"=INDEX(lr_state,{n})")
        f_grey(ws, f"C{t}", "=nr_TermMonths", FMT_INT)  # one LOB per workbook (D37)
        f_grey(ws, f"D{t}", f"=IF(COUNTIF(se_state,$B{t})=0,0,MATCH($B{t},se_state,0))", FMT_INT)
        f_grey(ws, f"E{t}", f"=IF($D{t}=0,0,INDEX(se_sum,$D{t}))", "0.00")
        f_grey(ws, f"F{t}", f"=IF(N(INDEX(lr_mind,{n}))=0,1,INDEX(lr_mind,{n}))", FMT_MOD)
        f_grey(ws, f"G{t}", f"=IF(N(INDEX(lr_m0,{n}))=0,1,INDEX(lr_m0,{n}))", FMT_MOD)
        f_grey(ws, f"H{t}",
               f"=IF(N(INDEX(lr_m0asof,{n}))=0,DATE(nr_PlanYear-1,10,1),INDEX(lr_m0asof,{n}))",
               "mm/dd/yyyy")
        f_grey(ws, f"I{t}", f"=IF(N(INDEX(lr_m1,{n}))=0,1,INDEX(lr_m1,{n}))", FMT_MOD)
        f_grey(ws, f"J{t}", f"=INDEX(lr_mprior,{n})", FMT_MOD)
        f_grey(ws, f"K{t}", f"=INDEX(lr_m2,{n})", FMT_MOD)
        # net-rate-selection cells (D39): mode, x(P), x(P+1), mod-adj-in-force
        f_grey(ws, f"L{t}", f"=NOT(ISBLANK(INDEX(lr_netp,{n})))")
        f_grey(ws, f"M{t}", f"=N(INDEX(lr_netp,{n}))", "0.0%")
        f_grey(ws, f"N{t}",
               f"=IF(ISBLANK(INDEX(lr_netp1,{n})),$M${t},N(INDEX(lr_netp1,{n})))", "0.0%")
        f_grey(ws, f"O{t}",
               f'=IF(AND(nr_ModAdjMaster="ON",INDEX(lr_modadj,{n})="ON"),1,0)', FMT_INT)
        anchors = write_mod_anchor_cells(
            ws, ctx, t + 1, 1,
            mind_ref=f"$F${t}", m0_ref=f"$G${t}", asof_ref=f"$H${t}",
            m1_ref=f"$I${t}", mprior_ref=f"$J${t}", m2_ref=f"$K${t}")
        blk = write_cohort_block(
            ws, ctx, t + 3, LogRefs(key_cond=f"$A${t}"), t_ref=f"$C${t}",
            srow_ref=f"$D${t}", ssum_ref=f"$E${t}", anchors=anchors,
            header=True, header_row_at=t + 2,
            net=dict(mode=f"$L${t}", x=f"$M${t}", x1=f"$N${t}",
                     modeff=f"$O${t}=1", mind=f"$F${t}"))
        # block results row
        rr = t + 51
        label(ws, f"A{rr}", "block results:")
        _grey(ws, f"A{rr}")
        f_grey(ws, f"B{rr}", f'=EXP(SUMPRODUCT((rl_key=$A${t})*(rl_cons="Y")*rl_ln1p))', FMT_IDX)
        for cL, ec in (("C", blk["ec_pm1"]), ("D", blk["ec_p"]), ("E", blk["ec_p1"])):
            f_grey(ws, f"{cL}{rr}",
                   f"=SUMPRODUCT({blk['w']},{ec},{blk['U']})/SUMPRODUCT({blk['w']},{ec})",
                   FMT_IDX)
        for cL, ec in (("F", blk["ec_p"]), ("G", blk["ec_p1"])):
            f_grey(ws, f"{cL}{rr}",
                   f"=SUMPRODUCT({blk['w']},{ec},{blk['Mw']})/SUMPRODUCT({blk['w']},{ec})",
                   FMT_MOD)

    # ------------------------------------------------------------------
    # 1. Results table rows 4..21 (linked by Portfolio via calc_* names)
    # ------------------------------------------------------------------
    hdr = ["key", "T", "CRL", "E_CY(P-1)", "E_CY(P)", "E_CY(P+1)", "Mbar(P)", "Mbar(P+1)",
           "A_rate(P)", "A_rate(P+1)", "A_mod(P)", "A_mod(P+1)", "LR_current",
           "CY LR(P)", "CY LR(P+1)", "EChg vs ind", "Carryover", "A_other", "trend"]
    for j, h in enumerate(hdr):
        put(ws, f"{col(1 + j)}{L.CALC_RES_HDR}", h, fnt=font(GREY_DARK, bold=True, size=9))
    for i in range(L.LR_ROWS):
        n = i + 1
        r = L.CALC_RES_FIRST + i
        t = block_tops[i]
        rr = t + 51
        f_grey(ws, f"A{r}", f"=$A${t}")
        f_grey(ws, f"B{r}", f"=$C${t}", FMT_INT)
        f_grey(ws, f"C{r}", f"=$B${rr}", FMT_IDX)
        f_grey(ws, f"D{r}", f"=$C${rr}", FMT_IDX)
        f_grey(ws, f"E{r}", f"=$D${rr}", FMT_IDX)
        f_grey(ws, f"F{r}", f"=$E${rr}", FMT_IDX)
        f_grey(ws, f"G{r}", f"=$F${rr}", FMT_MOD)
        f_grey(ws, f"H{r}", f"=$G${rr}", FMT_MOD)
        f_grey(ws, f"I{r}", f"=$C{r}/$E{r}", FMT_IDX)
        f_grey(ws, f"J{r}", f"=$C{r}/$F{r}", FMT_IDX)
        f_grey(ws, f"K{r}",
               f'=IF($L${t},1,IF(AND(nr_ModAdjMaster="ON",INDEX(lr_modadj,{n})="ON"),'
               f"$F${t}/$G{r},1))", FMT_IDX)
        f_grey(ws, f"L{r}",
               f'=IF($L${t},1,IF(AND(nr_ModAdjMaster="ON",INDEX(lr_modadj,{n})="ON"),'
               f"$F${t}/$H{r},1))", FMT_IDX)
        f_grey(ws, f"M{r}",
               f'=IF(INDEX(lr_basis,{n})="proposed",N(INDEX(lr_lrproj,{n}))*(1+N(INDEX(lr_s,{n}))),'
               f"N(INDEX(lr_lrproj,{n})))", "0.0%")
        f_grey(ws, f"R{r}", f"=IF(N(INDEX(lr_aother,{n}))=0,1,INDEX(lr_aother,{n}))", FMT_IDX)
        # effective trend: blank tbl_LR cell inherits the Control default (D38)
        f_grey(ws, f"S{r}",
               f"=IF(ISBLANK(INDEX(lr_trend,{n})),N(nr_TrendDefault),N(INDEX(lr_trend,{n})))",
               "0.0%")
        f_grey(ws, f"N{r}", f"=$M{r}*$I{r}*$K{r}*$R{r}", "0.0%")
        f_grey(ws, f"O{r}", f"=$M{r}*(1+$S{r})*$J{r}*$L{r}*$R{r}", "0.0%")
        f_grey(ws, f"P{r}", f"=$E{r}/$C{r}-1", "0.0%")
        f_grey(ws, f"Q{r}", f"=$F{r}/$E{r}-1", "0.0%")
        # State Summary support: dimension echoes, adjusted EP, and EP-weighted
        # numerators (metric x EP) so the exhibit aggregates via short SUMIFS (D38)
        f_grey(ws, f"T{r}", f"=INDEX(lr_state,{n})")
        f_grey(ws, f"U{r}", f"=INDEX(lr_bu,{n})")
        f_grey(ws, f"V{r}", f"=N(INDEX(lr_ep,{n}))", "#,##0")
        f_grey(ws, f"W{r}", f"=N(INDEX(lr_mind,{n}))*$V{r}", FMT_IDX)
        f_grey(ws, f"X{r}", f"=N(INDEX(lr_m0,{n}))*$V{r}", FMT_IDX)
        f_grey(ws, f"Y{r}", f"=N(INDEX(lr_m1,{n}))*$V{r}", FMT_IDX)
        f_grey(ws, f"Z{r}", f"=$C{r}*$V{r}", FMT_IDX)
        f_grey(ws, f"AA{r}", f"=$E{r}*$V{r}", FMT_IDX)
        f_grey(ws, f"AB{r}", f"=$I{r}*$V{r}", FMT_IDX)
        f_grey(ws, f"AC{r}", f"=$G{r}*$V{r}", FMT_IDX)
        f_grey(ws, f"AD{r}", f"=$K{r}*$V{r}", FMT_IDX)
        f_grey(ws, f"AE{r}", f"=$M{r}*$V{r}", FMT_IDX)
        f_grey(ws, f"AF{r}", f"=$N{r}*$V{r}", FMT_IDX)
        f_grey(ws, f"AG{r}", f"=$S{r}*$V{r}", FMT_IDX)
        f_grey(ws, f"AH{r}", f"=$J{r}*$V{r}", FMT_IDX)
        f_grey(ws, f"AI{r}", f"=$L{r}*$V{r}", FMT_IDX)
        f_grey(ws, f"AJ{r}", f"=$O{r}*$V{r}", FMT_IDX)
        f_grey(ws, f"AK{r}", f"=IF($L${t},1,0)", FMT_INT)
        f_grey(ws, f"AL{r}", f"=IF($L${t},$M${t},0)", "0.0%")
    res_names = {
        "calc_key": ("A", "Combo keys, aligned 1:1 with tbl_LR rows"),
        "calc_term": ("B", "Policy term by combo"),
        "calc_crl": ("C", "CRL_ind by combo"),
        "calc_ecy_pm1": ("D", "E_CY(P-1) by combo"), "calc_ecy_p": ("E", "E_CY(P) by combo"),
        "calc_ecy_p1": ("F", "E_CY(P+1) by combo"),
        "calc_mbar_p": ("G", "CY P earned mod by combo"),
        "calc_mbar_p1": ("H", "CY P+1 earned mod by combo"),
        "calc_arate_p": ("I", "A_rate(P) by combo"), "calc_arate_p1": ("J", "A_rate(P+1) by combo"),
        "calc_amod_p": ("K", "A_mod(P) by combo"), "calc_amod_p1": ("L", "A_mod(P+1) by combo"),
        "calc_lrcur": ("M", "LR at current rate level by combo"),
        "calc_cylr_p": ("N", "CY plan LR(P) by combo"),
        "calc_cylr_p1": ("O", "CY LR(P+1) indicative by combo"),
        "calc_echg": ("P", "CY earned rate chg vs indication by combo"),
        "calc_carry": ("Q", "Carryover into P+1 by combo"),
        "calc_aother": ("R", "A_other by combo (1 when blank)"),
        "calc_trend": ("S", "Effective P+1 net trend by combo (blank inherits the default)"),
        "calc_state": ("T", "State echo, aligned with tbl_LR rows"),
        "calc_bu": ("U", "BU echo, aligned with tbl_LR rows"),
        "calc_ep": ("V", "Adjusted plan EP by combo (0 when blank)"),
        "calc_w_mind": ("W", "M_ind x EP (State Summary weighting)"),
        "calc_w_m0": ("X", "M_0 x EP"), "calc_w_m1": ("Y", "M_1 x EP"),
        "calc_w_crl": ("Z", "CRL_ind x EP"), "calc_w_ecy": ("AA", "E_CY(P) x EP"),
        "calc_w_arate": ("AB", "A_rate(P) x EP"), "calc_w_mbar": ("AC", "Earned mod(P) x EP"),
        "calc_w_amod": ("AD", "A_mod(P) x EP"), "calc_w_lrcur": ("AE", "LR_current x EP"),
        "calc_w_cylr": ("AF", "CY plan LR(P) x EP"), "calc_w_trend": ("AG", "Net trend x EP"),
        "calc_w_arate1": ("AH", "A_rate(P+1) x EP"), "calc_w_amod1": ("AI", "A_mod(P+1) x EP"),
        "calc_w_cylr1": ("AJ", "CY LR(P+1) x EP"),
        "calc_netmode": ("AK", "1 when the combo carries a net rate selection (D39)"),
        "calc_netx": ("AL", "Net selection x(P) by combo (0 when off)"),
    }
    for name, (cL, desc) in res_names.items():
        ctx.define(name, "_calc", f"${cL}${L.CALC_RES_FIRST}:${cL}${L.CALC_RES_LAST}", desc)

    # ------------------------------------------------------------------
    # 3. Scenario section (selected combo)
    # ------------------------------------------------------------------
    sl = block_tops[-1] + L.CALC_BLOCK_STRIDE + 2          # scenario log header row
    put(ws, f"A{sl}", "Scenario-transformed rate logs (S1..S4), row-aligned with tbl_RateLog",
        fnt=font(GREY_DARK, bold=True, size=9))
    sc_logs = []
    for s in range(1, 5):
        c0 = 1 + (s - 1) * 10  # A, K, U, AE
        cEff, cEm, cAch, cReff, cLn, cDay, cEcnt, cScnt, cFirst = (col(c0 + j) for j in range(9))
        for j, h in enumerate(["eff'", "effmo'", "ach'", "r_eff'", "ln'", "days'", "ecnt", "scnt",
                               "first'"]):
            put(ws, f"{col(c0 + j)}{sl + 1}", f"S{s} {h}", fnt=font(GREY_DARK, size=8))
        r0 = sl + 2
        for j in range(L.RL_ROWS):
            r = r0 + j
            ir = L.RL_FIRST + j
            f_grey(ws, f"{cEff}{r}",
                   f'=IF({RL}!$C${ir}="","",IF({RL}!$E${ir}="planned",'
                   f"EDATE({RL}!$C${ir},N(INDEX(sc_shift,{s}))),{RL}!$C${ir}))", "mm/dd/yyyy")
            f_grey(ws, f"{cEm}{r}",
                   f'=IF(${cEff}{r}="","",DATE(YEAR(${cEff}{r}),MONTH(${cEff}{r}),1))',
                   "mm/dd/yyyy")
            f_grey(ws, f"{cAch}{r}",
                   f'=IF(N(INDEX(sc_ach,{s}))=0,IF({RL}!$G${ir}="",1,{RL}!$G${ir}),'
                   f"INDEX(sc_ach,{s}))", "0.0%")
            f_grey(ws, f"{cReff}{r}",
                   f'=IF({RL}!$C${ir}="",0,IF({RL}!$E${ir}="planned",'
                   f"({RL}!$D${ir}+N(INDEX(sc_dpts,{s})))*${cAch}{r},{RL}!$D${ir}))", "0.0%")
            f_grey(ws, f"{cLn}{r}",
                   f'=IF({RL}!$C${ir}="",0,IF(1+${cReff}{r}>0,LN(1+${cReff}{r}),0))', FMT_IDX)
            f_grey(ws, f"{cDay}{r}",
                   f'=IF(${cEff}{r}="",0,EOMONTH(${cEff}{r},0)-${cEff}{r}+1)', FMT_INT)
            f_grey(ws, f"{cEcnt}{r}",
                   f'=IF(${cEff}{r}="",0,COUNTIFS(rl_key,{RL}!$J${ir},'
                   f'${cEm}${r0}:${cEm}${r0 + L.RL_ROWS - 1},${cEm}{r},'
                   f'${cEff}${r0}:${cEff}${r0 + L.RL_ROWS - 1},"<"&${cEff}{r}))', FMT_INT)
            f_grey(ws, f"{cScnt}{r}",
                   f'=IF(${cEff}{r}="",0,COUNTIFS({RL}!$J${L.RL_FIRST}:$J${ir},{RL}!$J${ir},'
                   f"${cEm}${r0}:${cEm}{r},${cEm}{r},${cEff}${r0}:${cEff}{r},${cEff}{r}))",
                   FMT_INT)
            f_grey(ws, f"{cFirst}{r}",
                   f'=IF(${cEff}{r}="",0,IF(AND(${cEcnt}{r}=0,${cScnt}{r}=1),1,0))', FMT_INT)
        sc_logs.append(dict(
            eff=f"${cEff}${r0}:${cEff}${r0 + L.RL_ROWS - 1}",
            effmonth=f"${cEm}${r0}:${cEm}${r0 + L.RL_ROWS - 1}",
            ln=f"${cLn}${r0}:${cLn}${r0 + L.RL_ROWS - 1}",
            daysafter=f"${cDay}${r0}:${cDay}${r0 + L.RL_ROWS - 1}",
            first=f"${cFirst}${r0}:${cFirst}${r0 + L.RL_ROWS - 1}",
        ))

    sb = sl + L.RL_ROWS + 4
    ctx.lay_dyn["scenario_results"] = []
    for s in range(1, 5):
        t = sb + (s - 1) * L.CALC_BLOCK_STRIDE
        put(ws, f"A{t}", f"Scenario S{s} engine block (selected combo)",
            fnt=font(GREY_DARK, bold=True, size=9))
        anchors = write_mod_anchor_cells(
            ws, ctx, t + 1, 1, mind_ref="nr_MInd", m0_ref="nr_M0", asof_ref="nr_M0Asof",
            m1_ref="nr_M1", mprior_ref="nr_MPrior", m2_ref="nr_M2",
            dm1_expr=f"+N(INDEX(sc_dm1,{s}))")
        lg = sc_logs[s - 1]
        blk = write_cohort_block(
            ws, ctx, t + 3,
            LogRefs(key_cond="nr_SelKey", eff=lg["eff"], ln=lg["ln"],
                    effmonth=lg["effmonth"], first=lg["first"], daysafter=lg["daysafter"]),
            t_ref="nr_TermMonths", srow_ref="re_srow", ssum_ref="re_ssum",
            anchors=anchors, header=True, header_row_at=t + 2,
            net=dict(mode="nr_NetMode",
                     x=f"(nr_NetSelP+N(INDEX(sc_dnet,{s})))",
                     x1=f"(nr_NetSelP1+N(INDEX(sc_dnet,{s})))",
                     modeff='nr_ModAdjEff="ON"', mind="nr_MInd"))
        rr = t + 51
        label(ws, f"A{rr}", f"S{s} results:")
        _grey(ws, f"A{rr}")
        f_grey(ws, f"B{rr}",
               f"=SUMPRODUCT({blk['w']},{blk['ec_p']},{blk['U']})/SUMPRODUCT({blk['w']},{blk['ec_p']})",
               FMT_IDX)
        f_grey(ws, f"C{rr}",
               f"=SUMPRODUCT({blk['w']},{blk['ec_p1']},{blk['U']})/SUMPRODUCT({blk['w']},{blk['ec_p1']})",
               FMT_IDX)
        f_grey(ws, f"D{rr}",
               f"=SUMPRODUCT({blk['w']},{blk['ec_p']},{blk['Mw']})/SUMPRODUCT({blk['w']},{blk['ec_p']})",
               FMT_MOD)
        ctx.lay_dyn["scenario_results"].append(
            dict(e_p=f"'_calc'!$B${rr}", e_p1=f"'_calc'!$C${rr}", mbar_p=f"'_calc'!$D${rr}"))

    # ------------------------------------------------------------------
    # 4. Attribution section (selected combo)
    # ------------------------------------------------------------------
    al = sb + 4 * L.CALC_BLOCK_STRIDE + 2
    put(ws, f"A{al}", "Attribution: planned-row ranks and transformed logs (selected combo)",
        fnt=font(GREY_DARK, bold=True, size=9))
    for j, h in enumerate(["rank", "r_eff mag", "ln mag", "eff act", "effmo act", "days act",
                           "ecnt", "scnt", "first act"]):
        put(ws, f"{col(1 + j)}{al + 1}", h, fnt=font(GREY_DARK, size=8))
    r0 = al + 2
    for j in range(L.RL_ROWS):
        r = r0 + j
        ir = L.RL_FIRST + j
        f_grey(ws, f"A{r}",
               f'=IF(OR({RL}!$J${ir}<>nr_SelKey,{RL}!$E${ir}<>"planned",{RL}!$C${ir}=""),0,'
               f'COUNTIFS({RL}!$J${L.RL_FIRST}:$J${ir},nr_SelKey,'
               f'{RL}!$E${L.RL_FIRST}:$E${ir},"planned"))', FMT_INT)
        f_grey(ws, f"B{r}",
               f"=IF($A{r}=0,N({RL}!$K${ir}),IF(ISBLANK(INDEX(att_actpct,$A{r})),"
               f"N({RL}!$K${ir}),INDEX(att_actpct,$A{r})))", "0.0%")
        f_grey(ws, f"C{r}",
               f'=IF({RL}!$C${ir}="",0,IF(1+$B{r}>0,LN(1+$B{r}),0))', FMT_IDX)
        f_grey(ws, f"D{r}",
               f'=IF({RL}!$C${ir}="","",IF($A{r}=0,{RL}!$C${ir},'
               f"IF(ISBLANK(INDEX(att_actdate,$A{r})),{RL}!$C${ir},INDEX(att_actdate,$A{r}))))",
               "mm/dd/yyyy")
        f_grey(ws, f"E{r}", f'=IF($D{r}="","",DATE(YEAR($D{r}),MONTH($D{r}),1))', "mm/dd/yyyy")
        f_grey(ws, f"F{r}", f'=IF($D{r}="",0,EOMONTH($D{r},0)-$D{r}+1)', FMT_INT)
        f_grey(ws, f"G{r}",
               f'=IF($D{r}="",0,COUNTIFS(rl_key,{RL}!$J${ir},'
               f'$E${r0}:$E${r0 + L.RL_ROWS - 1},$E{r},$D${r0}:$D${r0 + L.RL_ROWS - 1},"<"&$D{r}))', FMT_INT)
        f_grey(ws, f"H{r}",
               f'=IF($D{r}="",0,COUNTIFS({RL}!$J${L.RL_FIRST}:$J${ir},{RL}!$J${ir},'
               f"$E${r0}:$E{r},$E{r},$D${r0}:$D{r},$D{r}))", FMT_INT)
        f_grey(ws, f"I{r}", f'=IF($D{r}="",0,IF(AND($G{r}=0,$H{r}=1),1,0))', FMT_INT)
    ctx.lay_dyn["att_rank"] = f"'_calc'!$A${r0}:$A${r0 + L.RL_ROWS - 1}"
    mag_ln = f"$C${r0}:$C${r0 + L.RL_ROWS - 1}"
    act_eff = f"$D${r0}:$D${r0 + L.RL_ROWS - 1}"
    act_em = f"$E${r0}:$E${r0 + L.RL_ROWS - 1}"
    act_day = f"$F${r0}:$F${r0 + L.RL_ROWS - 1}"
    act_first = f"$I${r0}:$I${r0 + L.RL_ROWS - 1}"

    ab = al + L.RL_ROWS + 4
    # magnitude block: achieved % at planned dates (rate only)
    t = ab
    put(ws, f"A{t}", "Attribution block 1 — rate magnitude (achieved % at planned dates)",
        fnt=font(GREY_DARK, bold=True, size=9))
    blk = write_cohort_block(
        ws, ctx, t + 3, LogRefs(key_cond="nr_SelKey", ln=mag_ln),
        t_ref="nr_TermMonths", srow_ref="re_srow", ssum_ref="re_ssum",
        anchors=None, include_mod=False, header=True, header_row_at=t + 2)
    rr = t + 51
    f_grey(ws, f"B{rr}",
           f"=SUMPRODUCT({blk['w']},{blk['ec_p']},{blk['W']})/SUMPRODUCT({blk['w']},{blk['ec_p']})",
           FMT_IDX)
    ctx.lay_dyn["att_e_mag"] = f"'_calc'!$B${rr}"

    # timing block: achieved % at actual dates
    t = ab + L.CALC_BLOCK_STRIDE
    put(ws, f"A{t}", "Attribution block 2 — rate timing (achieved % at actual dates)",
        fnt=font(GREY_DARK, bold=True, size=9))
    blk = write_cohort_block(
        ws, ctx, t + 3,
        LogRefs(key_cond="nr_SelKey", eff=act_eff, ln=mag_ln, effmonth=act_em,
                first=act_first, daysafter=act_day),
        t_ref="nr_TermMonths", srow_ref="re_srow", ssum_ref="re_ssum",
        anchors=None, include_mod=False, header=True, header_row_at=t + 2)
    rr = t + 51
    f_grey(ws, f"B{rr}",
           f"=SUMPRODUCT({blk['w']},{blk['ec_p']},{blk['W']})/SUMPRODUCT({blk['w']},{blk['ec_p']})",
           FMT_IDX)
    ctx.lay_dyn["att_e_time"] = f"'_calc'!$B${rr}"

    # actual-mod block
    t = ab + 2 * L.CALC_BLOCK_STRIDE
    put(ws, f"A{t}", "Attribution block 3 — actual written-mod path",
        fnt=font(GREY_DARK, bold=True, size=9))
    f_grey(ws, f"M{t}", "=IF(N(att_m0)=0,nr_M0,att_m0)", FMT_MOD)
    f_grey(ws, f"N{t}", "=IF(N(att_asof)=0,nr_M0Asof,att_asof)", "mm/dd/yyyy")
    f_grey(ws, f"O{t}", "=IF(N(att_m1)=0,nr_M1,att_m1)", FMT_MOD)
    f_grey(ws, f"P{t}", "=IF(N(att_m2)=0,N(nr_M2),att_m2)", FMT_MOD)
    anchors = write_mod_anchor_cells(
        ws, ctx, t + 1, 1, mind_ref="nr_MInd", m0_ref=f"$M${t}", asof_ref=f"$N${t}",
        m1_ref=f"$O${t}", mprior_ref="nr_MPrior", m2_ref=f"$P${t}")
    blk = write_cohort_block(
        ws, ctx, t + 3, LogRefs(key_cond="nr_SelKey"), t_ref="nr_TermMonths",
        srow_ref="re_srow", ssum_ref="re_ssum", anchors=anchors,
        include_rate=False, header=True, header_row_at=t + 2)
    rr = t + 51
    f_grey(ws, f"B{rr}",
           f"=SUMPRODUCT({blk['w']},{blk['ec_p']},{blk['Mw']})/SUMPRODUCT({blk['w']},{blk['ec_p']})",
           FMT_MOD)
    ctx.lay_dyn["att_mbar_act"] = f"'_calc'!$B${rr}"

    # ------------------------------------------------------------------
    # 5. Solver base block (taken rows only) + cumulative columns
    # ------------------------------------------------------------------
    t = ab + 3 * L.CALC_BLOCK_STRIDE
    put(ws, f"A{t}", "Solver base block — taken rows only (planned program excluded, D13); "
                     "keyed on slv_key so the Solver can follow Control OR its own override",
        fnt=font(GREY_DARK, bold=True, size=9))
    # local seasonality for the SOLVE combo's state (may differ from the selection)
    f_grey(ws, f"M{t}", "=IF(COUNTIF(se_state,slv_state)=0,0,MATCH(slv_state,se_state,0))",
           FMT_INT)
    f_grey(ws, f"N{t}", f"=IF($M${t}=0,0,INDEX(se_sum,$M${t}))", "0.00")
    # first="rl_firsttaken": the split flag must be STATUS-AWARE — the plain
    # rl_first is filter-blind, and a planned row earlier in a taken row's
    # cohort month would steal the flag, zero the L column, and silently drop
    # the taken change from that cohort's W0 (D58; oracle filters first).
    blk = write_cohort_block(
        ws, ctx, t + 3, LogRefs(key_cond="slv_key", taken_only=True,
                                first="rl_firsttaken"),
        t_ref="nr_TermMonths", srow_ref=f"$M${t}", ssum_ref=f"$N${t}",
        anchors=None, include_mod=False, header=True, header_row_at=t + 2)
    bf, bl = blk["first"], blk["last"]
    put(ws, f"S{t + 2}", "w-ec-W0", fnt=font(GREY_DARK, size=8))
    put(ws, f"T{t + 2}", "cum", fnt=font(GREY_DARK, size=8))
    put(ws, f"U{t + 2}", "w-ec-W0eom", fnt=font(GREY_DARK, size=8))
    for i in range(L.N_COH):
        r = bf + i
        f_grey(ws, f"S{r}", f"=$H{r}*$Q{r}*$N{r}", FMT_IDX)
        f_grey(ws, f"T{r}", f"=SUM($S${bf}:$S{r})", FMT_IDX)
        f_grey(ws, f"U{r}", f"=$H{r}*$Q{r}*$J{r}", FMT_IDX)
    rr = t + 51
    label(ws, f"A{rr}", "solver totals:")
    _grey(ws, f"A{rr}")
    f_grey(ws, f"B{rr}", f"=SUMPRODUCT({blk['w']},{blk['ec_p']})", FMT_IDX)   # D
    f_grey(ws, f"C{rr}", f"=SUM($S${bf}:$S${bl})", FMT_IDX)                   # total blend
    ctx.lay_dyn["solver"] = dict(first=bf, last=bl)
    slv_names = {
        "slv_absmi": (f"$G${bf}:$G${bl}", "Solver block: absolute cohort month indices"),
        "slv_w": (f"$H${bf}:$H${bl}", "Solver block: written weights"),
        "slv_ecp": (f"$Q${bf}:$Q${bl}", "Solver block: CY P earning fractions"),
        "slv_widx": (f"$N${bf}:$N${bl}", "Solver block: taken-only written index W0 (blended)"),
        "slv_wpre": (f"$I${bf}:$I${bl}", "Solver block: pre-month index W0_pre"),
        "slv_weom": (f"$J${bf}:$J${bl}", "Solver block: end-of-month index W0_eom"),
        "slv_dfirst": (f"$L${bf}:$L${bl}", "Solver block: first-taken-change days on/after"),
        "slv_cum": (f"$T${bf}:$T${bl}", "Solver block: cumulative w-ec-W0"),
        "slv_weom_c": (f"$U${bf}:$U${bl}", "Solver block: w-ec-W0_eom by cohort"),
        "slv_den": (f"$B${rr}", "Solver denominator D = SUM w-ec over CY P"),
        "slv_total": (f"$C${rr}", "Solver total SUM w-ec-W0 over CY P"),
    }
    for name, (ref, desc) in slv_names.items():
        ctx.define(name, "_calc", ref, desc)
